config/routes.rb
Rails.application.routes.draw do

  root 'shops#index'

   devise_for :users, controllers:{
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
   }

  resources :shops




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord

belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :shops


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

 before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
    end

end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

def index
  @shops = Shop.all
end

def new
  @shop = Shop.new
end

def create
  @shop = Shop.new(shops_params)
  if @shop.save
    redirect_to root_path,notice: "ショップ登録完了"
  else
    render :new
  end
end

def show
  @shop = Shop.find(params[:id])
end

def edit
  @shop = Shop.find(params[:id])
end

def update
  shop = Shop.find(params[:id])
  if shop.update(shops_params)
    redirect_to shop_path,nitice: "更新完了"
  else
    render :edit
  end
end

def destroy
  shop = Shop.find(params[:id])
  if shop.destroy
    redirect_to root_path,notice: "削除完了"
  else
    render :show
  end
end


private

def shops_params
  params.require(:shop).permit(:name,:name_kana,:copy,:founded,:openning,:closed,:town_number,:tel_number,:fax_number,:email,:url,:map_api,:switching_publiation).merge(user_id:current_user.id)
end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title
      = content_for?(:title) ? yield(:title) : "商店街"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    .notice
      = notice
    = yield

app/views/shops/_menu.html.haml
%h1 商店街
.header_image
%ul.nav
  %li.nav__item
    = link_to "サインアップ" , new_user_registration_path
  %li.nav__item
    = link_to "ログイン" , new_user_session_path
  %li.nav__item
    = link_to "ログアウト" , destroy_user_session_path, method: :delete
  %li.nav__item
    = link_to "ユーザー編集" , edit_user_registration_path
  %li.nav__item
    = link_to "ショップ登録", new_shop_path

app/views/shops/_shop.html.haml
- if shop.switching_publiation == 1
  .shop_wrapper.float
    .shop__info
      .shop__info--image
        = image_tag("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTp_R7wn3zQmCuRTqdXBlsl9tUGCaeZn9po19O8dHF1QfnchdGXgA")
      .shop__info--name
        店舗名：
        = shop.name
      .shop__info--name_kana
        店舗名（カナ）：
        = shop.name_kana
      .shop__info--copy
        コピー：
        = shop.copy
      .shop__show
        = link_to '店舗詳細',"/shops/#{shop.id}",method: :get

app/views/shops/_shop_form.html.haml
= form_for(shop) do |f|

  .field
    = f.label "店名"
    = f.text_field :name, autofocus: true

  .field
    = f.label "店名（カナ）"
    = f.text_field :name_kana

  .field
    = f.label "キャッチコピー"
    = f.text_field :copy

  .field
    = f.label "設立"
    = f.text_field :founded

  .field
    = f.label "営業時間"
    = f.text_field :openning

  .field
    = f.label "定休日"
    = f.text_field :closed

  .field
    = f.label "番街（番号）"
    = f.text_field :town_number

  .field
    = f.label "電話番号"
    = f.text_field :tel_number

  .field
    = f.label "FAX番号"
    = f.text_field :fax_number

  .field
    = f.label "E-mail"
    = f.email_field :email

  .field
    = f.label "お店のHP（URL）"
    = f.text_field :url

  .field
    = f.label "地図情報（API_key）"
    = f.text_field :map_api

  .field
    = f.label "公開/非公開"
    = f.text_field :switching_publiation

  .actions
    = f.submit "登録"

app/views/shops/edit.html.haml
%h2 Shop情報登録

= render partial: "shop_form", locals: { shop: @shop }

app/views/shops/index.html.haml
- content_for :title do
  商店街TOP

= render 'menu'

= render @shops

app/views/shops/new.html.haml
%h2 Shop情報登録

= form_for(@shops) do |f|

  .field
    = f.label "店名"
    = f.text_field :name, autofocus: true

  .field
    = f.label "店名（カナ）"
    = f.text_field :name_kana

  .field
    = f.label "キャッチコピー"
    = f.text_field :copy

  .field
    = f.label "設立"
    = f.text_field :founded

  .field
    = f.label "営業時間"
    = f.text_field :openning

  .field
    = f.label "定休日"
    = f.text_field :closed

  .field
    = f.label "番街（番号）"
    = f.text_field :town_number

  .field
    = f.label "電話番号"
    = f.text_field :tel_number

  .field
    = f.label "FAX番号"
    = f.text_field :fax_number

  .field
    = f.label "E-mail"
    = f.email_field :email

  .field
    = f.label "お店のHP（URL）"
    = f.text_field :url

  .field
    = f.label "地図情報（API_key）"
    = f.text_field :map_api

  .field
    = f.label "公開/非公開"
    = f.text_field :switching_publiation

  .actions
    = f.submit "登録"

app/views/shops/show.html.haml
.shop__show
  .shop__show--image
    = image_tag ("http://www.ticketport.co.jp/shop/IMG_%E6%A2%85%E7%94%B0.JPG"), class: "shop__show--image--image-box"
  .shop__show--name
    店舗名：
    = @shop.name
  .shop__show--name_kana
    店舗名（カナ）：
    = @shop.name_kana
  .shop__show--copy
    コピー：
    = @shop.copy
  .shop__show--founded
    設立（年）：
    = @shop.founded
  .shop__show--oppening
    営業時間：
    = @shop.openning
  .shop__show--closed
    定休日：
    = @shop.closed
  .shop__show--town_number
    番街：
    = @shop.town_number
  .shop__show--tel_number
    電話番号：
    = @shop.tel_number
  .shop__show--fax_number
    ファックス番号：
    = @shop.fax_number
  .shop__show--email
    お問い合わせメール：
    = @shop.email
  .shop__show--url
    ホームページ：
    = @shop.url
  .shop__show--map_api
    地図情報：
    = @shop.map_api

.shop__show__edit
  = link_to "編集", edit_shop_path
.shop__show__destroy
  = link_to "削除", shop_path, method: :delete
.shop__show__back
  = link_to "戻る", root_path

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/